version: '3'

services:
    nginx:
        container_name: nginx_${APP_NAME}
        image: stenfrank/nginx:1.3
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/sites-available:/etc/nginx/sites-available
        networks:
            - network
        depends_on:
            - php
    php:
        container_name: php_${APP_NAME}
        restart: unless-stopped
        user: "${APP_USER}"
        build:
            args:
                user: app_user
                uid: "${APP_USER}"
            context: ./docker/php/
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - network
        depends_on:
            - database

    supervisor:
        build:
            context: ./docker/supervisor/
        container_name: supervisor_${APP_NAME}
        volumes:
            - ./:/var/www/html
        networks:
            - network

    database:
        container_name: database_${APP_NAME}
        image: mysql:8.0
        restart: unless-stopped
        volumes:
            - ./docker/mysql:/etc/mysql/conf.d
            - './docker/mysql/testing.sql:/docker-entrypoint-initdb.d/1-testing.sql'
            - volumedata:/var/lib/mysql
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "${APP_DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: ${APP_NAME}_user
            MYSQL_DATABASE: ${APP_NAME}_db
            MYSQL_PASSWORD: secret
        networks:
            - network

    phpmyadmin:
        container_name: phpmyadmin_${APP_NAME}
        depends_on:
            - database
        image: phpmyadmin
        restart: unless-stopped
        ports:
            - "${APP_PHPMYADMIN_PORT}:80"
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: password
            PMA_ABSOLUTE_URI: http://phpmyadmin/phpmyadmin/
        networks:
            - network

networks:
    network:
        name: ${APP_NAME}_network
        driver: "bridge"

volumes:
    volumedata:
        name: ${APP_NAME}_data
